language: go

sudo: required

go:
  - 1.15.3

go_import_path: github.com/root-gg/plik

before_script:
  - GO111MODULE=off go get -u golang.org/x/lint/golint

script:
  - make lint && make test && make test-backends && make release