name: Run tests

on: [push, pull_request]

jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
      
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Fetch tags
      run: |
        git fetch --prune --unshallow --tags

    - name: Run linter
      run: make lint

    - name: Run tests
      run: make test

    - name: Run test-backends
      run: make test-backends

    - name: Run release
      run: make release